//  Hello World server

#include "Car_builder.h" // Generated by `flatcc`.
#include "flatbuffers_common_builder.h"
#include <zmq.h>
#include <unistd.h>
#include <time.h>

#include "../inc/mosquitto/mosquitto.h"

#undef ns
#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(Test, x) // specified in the schema

static struct mosquitto* mosq = NULL;

struct Car {
    char name[10];
    char model[10];
    int year;
};

struct Car getRandomCar() {
    struct Car randomCar;
    int a = rand();
    if ((a % 2) == 0) {
        strcpy(randomCar.name, "Ford");
        strcpy(randomCar.model, "Focus");
    } else {
        strcpy(randomCar.name, "Dodge");
        strcpy(randomCar.model, "Charger");
    }
    randomCar.year = rand();
    return randomCar;
}

int main (void)
{
    srand(time(NULL));

	mosquitto_lib_init();
	mosq = mosquitto_new("pub", true, NULL);
	mosquitto_connect(mosq, "127.0.0.1", 8883, 0);

	struct Car c = getRandomCar();
	flatcc_builder_t builder, *B;
	B = &builder;
	flatcc_builder_init(B);

	uint8_t *buf;
	size_t size;

	flatbuffers_string_ref_t name = flatbuffers_string_create_str(B, c.name);
	flatbuffers_string_ref_t model = flatbuffers_string_create_str(B, c.model);

	ns(Car_start_as_root(B));
	ns(Car_name_add(B, name));
	ns(Car_model_add(B, model));
	ns(Car_year_add(B, c.year));
	ns(Car_end_as_root(B));
	buf = flatcc_builder_finalize_buffer(B, &size);

	mosquitto_publish(mosq, NULL, "test", size, buf,  0, false);

	free(buf);
	

//    //  Socket to talk to clients
//    void *context = zmq_ctx_new ();
//    void *responder = zmq_socket (context, ZMQ_REP);
//    int rc = zmq_bind (responder, "tcp://*:5555");
//    assert (rc == 0);
//    int counter = 0;
//
//    while (1) {
//        struct Car c = getRandomCar();
//
//        flatcc_builder_t builder, *B;
//        B = &builder;
//        // Initialize the builder object.
//        flatcc_builder_init(B);
//        uint8_t *buf; // raw buffer used by flatbuffer
//        size_t size; // the size of the flatbuffer
//        // Convert the char arrays to strings
//        flatbuffers_string_ref_t name = flatbuffers_string_create_str(B, c.name);
//        flatbuffers_string_ref_t model = flatbuffers_string_create_str(B, c.model);
//
//        ns(Car_start_as_root(B));
//        ns(Car_name_add(B, name));
//        ns(Car_model_add(B, model));
//        ns(Car_year_add(B, c.year));
//        ns(Car_end_as_root(B));
//        buf = flatcc_builder_finalize_buffer(B, &size);
//
//        char receiveBuffer [10];
//        zmq_recv (responder, receiveBuffer, 10, 0);
//        printf ("Received ready signal. Sending car %d.\n", counter);
//        sleep (1);          //  Do some 'work'
//        zmq_send (responder, buf, size, 0);
//        counter++;
//
//        free(buf);
//    }
    return 0;
}