//  Hello World client
#include "Car_builder.h" // Generated by `flatcc`.
#include "flatbuffers_common_builder.h"
#include "../inc/mosquitto/mosquitto.h"
#include <stdio.h>
#include <unistd.h>

#undef ns
#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(Test, x) // Specified in the schema

static struct mosquitto* mosq = NULL;
static void MQTT_on_message(struct mosquitto* mosq, void* obj, const struct mosquitto_message* message);
static void MQTT_on_subscribe(struct mosquitto * mosq, void * obj, int a, int b, const int * c);
static void ProcessMessage(const struct mosquitto_message* message);

struct Car {
    const char* name;
    const char* model;
    int year;
};

int main (void)
{
    printf ("Connecting to car world server...\n");

	mosquitto_lib_init();
	mosq = mosquitto_new("sub", true, NULL);

	mosquitto_message_callback_set(mosq, MQTT_on_message);
	mosquitto_subscribe_callback_set(mosq, MQTT_on_subscribe);

	mosquitto_connect(mosq, "127.0.0.1", 8883, 0);
	mosquitto_subscribe(mosq, NULL, "#", 0);
	mosquitto_loop_start(mosq);

	while (1) {
		sleep(1);
	};
    return 0;
}

static void MQTT_on_message(struct mosquitto* mosq, void* obj, const struct mosquitto_message* message)
{
	printf("Got a message!\n");
	ProcessMessage(message);
}
static void MQTT_on_subscribe(struct mosquitto * mosq, void * obj, int a, int b, const int * c)
{
	printf("We are subscribed \n");
}
static void ProcessMessage(const struct mosquitto_message* message)
{

	printf("message: %s\n", message->payload);

	ns(Car_table_t) car = ns(Car_as_root(message->payload));
	int year = ns(Car_year(car));
	flatbuffers_string_t model = ns(Car_model(car));
	flatbuffers_string_t name = ns(Car_name(car));

	struct Car nextCar;
	nextCar.model = model;
	nextCar.name = name;
	nextCar.year = year;

	printf("Name: %s, Model: %s, Year: %d\n", nextCar.name, nextCar.model, nextCar.year);
}